import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { MenubarComponent } from "@/components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.WEBSITE_TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <section className="pt-8 px-4">
            <MenubarComponent />
          </section>
          <main >
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  </>
  );
}
