import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { MenubarComponent } from "@/components/navigation";
import { ProfileLeft } from "@/components/left-profile-component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.WEBSITE_TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <section className="pt-8 px-4">
            <MenubarComponent />
          </section>
          <div className="flex flex-col md:flex-row py-6 px-3">
          <div>
            <ProfileLeft />
          </div>
          <main className="p-6">
            {children}
          </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
